// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using messages_task_api;

#nullable disable

namespace messagestaskapi.Migrations
{
    [DbContext(typeof(MessagesTaskContext))]
    [Migration("20230128230502_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("messages_task_api.Models.HistoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeLog")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HistoryLogs");
                });

            modelBuilder.Entity("messages_task_api.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4dfe286-3724-4a7f-a9b1-105c38c33e20"),
                            Body = "Hello Patrick how are you",
                            DateReceived = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderEmail = "toto@gmail.com",
                            UserId = new Guid("9c56cb08-8ac0-4682-9cc5-95eca841476c")
                        },
                        new
                        {
                            Id = new Guid("b0f4af03-a002-434f-b9ee-82f5a8ae9bc3"),
                            Body = "I hope you are fine",
                            DateReceived = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderEmail = "toto@gmail.com",
                            UserId = new Guid("9c56cb08-8ac0-4682-9cc5-95eca841476c")
                        });
                });

            modelBuilder.Entity("messages_task_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c56cb08-8ac0-4682-9cc5-95eca841476c"),
                            Email = "synry63@gmail.com",
                            PasswordHash = "C3TZb8Ef5NcKnL/1CmjTrvYsixij9REwLDVkoK2UvFs=",
                            PasswordSalt = "/DYD9vqoSbSJ9B9b8AoThQ=="
                        },
                        new
                        {
                            Id = new Guid("50960105-b80e-49b0-be10-e7ce36e67b8e"),
                            Email = "toto@gmail.com",
                            PasswordHash = "C3TZb8Ef5NcKnL/1CmjTrvYsixij9REwLDVkoK2UvFs=",
                            PasswordSalt = "/DYD9vqoSbSJ9B9b8AoThQ=="
                        });
                });

            modelBuilder.Entity("messages_task_api.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("messages_task_api.Models.HistoryLog", b =>
                {
                    b.HasOne("messages_task_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("messages_task_api.Models.Message", b =>
                {
                    b.HasOne("messages_task_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("messages_task_api.Models.UserNotification", b =>
                {
                    b.HasOne("messages_task_api.Models.User", "User")
                        .WithOne("userNotification")
                        .HasForeignKey("messages_task_api.Models.UserNotification", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("messages_task_api.Models.User", b =>
                {
                    b.Navigation("userNotification")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
